version: '3.8'

services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    networks:
      - n8n-network
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - fastapi_data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    networks:
      - n8n-network
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - fastapi

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data:
  fastapi_data: